## logistic regression

In [7]:
import numpy as np
import pandas as pd

In [2]:
train_file=r'E:\lanchan VIP files\data scienece\python\Data\rg_train.csv'
test_file=r'E:\lanchan VIP files\data scienece\python\Data\rg_test.csv'

In [3]:
bd_train=pd.read_csv(train_file)
bd_test=pd.read_csv(test_file)

In [4]:
bd_train

REF_NO children age_band                status         occupation  \
0       2148        1    45-50               Partner       Professional   
1       8099        1    61-65               Partner            Retired   
2       6611        3    31-35               Partner       Professional   
3       1950     Zero    55-60               Partner       Professional   
4      10857        2    51-55               Partner      Manual Worker   
5      10853        2    31-35               Partner       Professional   
6       1495        3    36-40               Partner  Secretarial/Admin   
7       9602        1    41-45               Partner              Other   
8       5402        2    26-30               Partner  Secretarial/Admin   
9       6343        3    31-35               Partner   Business Manager   
10      6370        3    26-30               Partner          Housewife   
11      2768        2    41-45               Partner  Secretarial/Admin   
12      8769        1    45-50               Partner      Manual Worker   
13      2097        1    26-30  Single/Never Married       Professional   
14      4672        1    45-50               Partner          Housewife   
15      9816     Zero    51-55               Partner          Housewife   
16     11226     Zero    65-70               Partner            Retired   
17      2614     Zero    61-65               Partner            Retired   
18      5135        2    36-40               Partner  Secretarial/Admin   
19       853     Zero    51-55               Partner  Secretarial/Admin   
20      7625        1    26-30               Partner  Secretarial/Admin   
21      4466        1    41-45    Divorced/Separated       Professional   
22      9630        1    55-60               Partner       Professional   
23      1738     Zero    65-70               Widowed            Retired   
24      4014        2    26-30               Partner              Other   
25      5632     Zero    45-50               Partner  Secretarial/Admin   
26      1724        2    51-55               Partner   Business Manager   
27      4123        3    31-35               Partner              Other   
28     11056        1    31-35               Partner          Housewife   
29      1529     Zero    51-55               Partner   Business Manager   
...      ...      ...      ...                   ...                ...   
8094   10305     Zero    55-60               Partner       Professional   
8095    3344     Zero    65-70               Partner          Housewife   
8096   11292     Zero    55-60               Partner          Housewife   
8097    4016        3    31-35               Partner       Professional   
8098    3516        2    41-45               Partner       Professional   
8099   11151        1    61-65               Partner            Retired   
8100    4203        1    41-45               Partner              Other   
8101    4903        1    36-40               Partner       Professional   
8102   10051     Zero    61-65               Partner            Retired   
8103    3216     Zero    55-60               Partner            Retired   
8104    5500     Zero    55-60               Partner            Unknown   
8105    6675        1    31-35               Partner              Other   
8106    5297     Zero    26-30               Partner  Secretarial/Admin   
8107    9465     Zero      71+               Partner            Unknown   
8108    6710        1    31-35               Partner  Secretarial/Admin   
8109    9492     Zero    55-60               Partner            Retired   
8110    6138        1    36-40               Partner   Business Manager   
8111    7668     Zero    26-30  Single/Never Married  Secretarial/Admin   
8112    5483        3    31-35               Partner          Housewife   
8113    2429     Zero    61-65               Partner            Retired   
8114    1626     Zero    55-60               Partner       Professional   
8115    3926     Zero    51-55 

In [5]:
bd_test

REF_NO children age_band                status         occupation  \
0          9        1    36-40               Partner       Professional   
1         13     Zero    61-65               Partner            Retired   
2         18     Zero    26-30               Partner            Unknown   
3         21        1    41-45               Partner  Secretarial/Admin   
4         26     Zero    26-30               Partner       Professional   
5         28     Zero      71+               Partner            Retired   
6         34     Zero    22-25               Partner       Professional   
7         44        2    36-40               Partner  Secretarial/Admin   
8         57     Zero    55-60    Divorced/Separated  Secretarial/Admin   
9         59     Zero    45-50               Partner       Professional   
10        64     Zero    55-60               Partner      Manual Worker   
11        67     Zero    45-50               Partner          Housewife   
12        71     Zero    61-65               Widowed            Retired   
13        79        1    45-50               Partner       Professional   
14        87     Zero    41-45  Single/Never Married  Secretarial/Admin   
15        89     Zero    45-50               Partner       Professional   
16       110     Zero    55-60               Partner       Professional   
17       113        2    26-30               Partner            Unknown   
18       114     Zero    61-65  Single/Never Married            Retired   
19       116     Zero    45-50               Partner            Retired   
20       123        3    36-40               Partner       Professional   
21       126     Zero    55-60               Partner            Retired   
22       129     Zero    55-60               Partner            Unknown   
23       130     Zero    51-55               Partner            Retired   
24       132        2    36-40               Partner       Professional   
25       138     Zero    26-30  Single/Never Married  Secretarial/Admin   
26       144     Zero    61-65               Partner            Retired   
27       147     Zero    26-30               Partner          Housewife   
28       149     Zero    55-60               Partner  Secretarial/Admin   
29       150     Zero    41-45               Partner            Unknown   
...      ...      ...      ...                   ...                ...   
2001   11362        2    31-35               Partner       Professional   
2002   11363        2    36-40               Partner       Professional   
2003   11369     Zero    51-55               Partner              Other   
2004   11373     Zero    55-60               Partner            Retired   
2005   11377        2    31-35               Partner       Professional   
2006   11380     Zero    65-70               Partner            Unknown   
2007   11382     Zero    31-35  Single/Never Married  Secretarial/Admin   
2008   11383     Zero    45-50               Partner  Secretarial/Admin   
2009   11386        2    36-40    Divorced/Separated  Secretarial/Admin   
2010   11398     Zero    51-55               Partner       Professional   
2011   11400        1    45-50               Partner       Professional   
2012   11410     Zero    41-45               Partner      Manual Worker   
2013   11412     Zero    45-50               Partner   Business Manager   
2014   11416        2    31-35               Partner          Housewife   
2015   11427     Zero    41-45               Partner       Professional   
2016   11433        1    26-30               Partner      Manual Worker   
2017   11444     Zero    61-65               Partner            Retired   
2018   11447     Zero    36-40               Partner       Professional   
2019   11450     Zero    26-30               Partner       Professional   
2020   11454     Zero    61-65               Partner            Retired   
2021   11470     Zero    22-25  Single/Never Married            Student   
2022   11474        1    55-60 

In [8]:
bd_test['Revenue.Grid']=np.nan

In [9]:
bd_test=bd_test[bd_train.columns]

In [10]:
bd_all=pd.concat([bd_train,bd_test],axis=0)

In [11]:
bd_all

REF_NO children age_band                status         occupation  \
0       2148        1    45-50               Partner       Professional   
1       8099        1    61-65               Partner            Retired   
2       6611        3    31-35               Partner       Professional   
3       1950     Zero    55-60               Partner       Professional   
4      10857        2    51-55               Partner      Manual Worker   
5      10853        2    31-35               Partner       Professional   
6       1495        3    36-40               Partner  Secretarial/Admin   
7       9602        1    41-45               Partner              Other   
8       5402        2    26-30               Partner  Secretarial/Admin   
9       6343        3    31-35               Partner   Business Manager   
10      6370        3    26-30               Partner          Housewife   
11      2768        2    41-45               Partner  Secretarial/Admin   
12      8769        1    45-50               Partner      Manual Worker   
13      2097        1    26-30  Single/Never Married       Professional   
14      4672        1    45-50               Partner          Housewife   
15      9816     Zero    51-55               Partner          Housewife   
16     11226     Zero    65-70               Partner            Retired   
17      2614     Zero    61-65               Partner            Retired   
18      5135        2    36-40               Partner  Secretarial/Admin   
19       853     Zero    51-55               Partner  Secretarial/Admin   
20      7625        1    26-30               Partner  Secretarial/Admin   
21      4466        1    41-45    Divorced/Separated       Professional   
22      9630        1    55-60               Partner       Professional   
23      1738     Zero    65-70               Widowed            Retired   
24      4014        2    26-30               Partner              Other   
25      5632     Zero    45-50               Partner  Secretarial/Admin   
26      1724        2    51-55               Partner   Business Manager   
27      4123        3    31-35               Partner              Other   
28     11056        1    31-35               Partner          Housewife   
29      1529     Zero    51-55               Partner   Business Manager   
...      ...      ...      ...                   ...                ...   
2001   11362        2    31-35               Partner       Professional   
2002   11363        2    36-40               Partner       Professional   
2003   11369     Zero    51-55               Partner              Other   
2004   11373     Zero    55-60               Partner            Retired   
2005   11377        2    31-35               Partner       Professional   
2006   11380     Zero    65-70               Partner            Unknown   
2007   11382     Zero    31-35  Single/Never Married  Secretarial/Admin   
2008   11383     Zero    45-50               Partner  Secretarial/Admin   
2009   11386        2    36-40    Divorced/Separated  Secretarial/Admin   
2010   11398     Zero    51-55               Partner       Professional   
2011   11400        1    45-50               Partner       Professional   
2012   11410     Zero    41-45               Partner      Manual Worker   
2013   11412     Zero    45-50               Partner   Business Manager   
2014   11416        2    31-35               Partner          Housewife   
2015   11427     Zero    41-45               Partner       Professional   
2016   11433        1    26-30               Partner      Manual Worker   
2017   11444     Zero    61-65               Partner            Retired   
2018   11447     Zero    36-40               Partner       Professional   
2019   11450     Zero    26-30               Partner       Professional   
2020   11454     Zero    61-65               Partner            Retired   
2021   11470     Zero    22-25  Single/Never Married            Student   
2022   11474        1    55-60 

In [12]:
bd_train.shape

(8124, 32)

In [13]:
bd_test.shape

(2031, 32)

In [14]:
bd_all.shape

(10155, 32)

In [15]:
bd_all['Revenue.Grid'].value_counts()

2.0    7261
1.0     863
Name: Revenue.Grid, dtype: int64

In [20]:
list(zip(bd_all.columns,bd_all.dtypes,bd_all.nunique()))

[('REF_NO', dtype('int64'), 10155),
 ('children', dtype('O'), 5),
 ('age_band', dtype('O'), 13),
 ('status', dtype('O'), 5),
 ('occupation', dtype('O'), 9),
 ('occupation_partner', dtype('O'), 9),
 ('home_status', dtype('O'), 5),
 ('family_income', dtype('O'), 13),
 ('self_employed', dtype('O'), 2),
 ('self_employed_partner', dtype('O'), 2),
 ('year_last_moved', dtype('int64'), 95),
 ('TVarea', dtype('O'), 14),
 ('post_code', dtype('O'), 10040),
 ('post_area', dtype('O'), 2039),
 ('Average.Credit.Card.Transaction', dtype('float64'), 1411),
 ('Balance.Transfer', dtype('float64'), 2183),
 ('Term.Deposit', dtype('float64'), 1419),
 ('Life.Insurance', dtype('float64'), 3111),
 ('Medical.Insurance', dtype('float64'), 1589),
 ('Average.A.C.Balance', dtype('float64'), 2223),
 ('Personal.Loan', dtype('float64'), 1760),
 ('Investment.in.Mutual.Fund', dtype('float64'), 2470),
 ('Investment.Tax.Saving.Bond', dtype('float64'), 832),
 ('Home.Loan', dtype('float64'), 884),
 ('Online.Purchase.Amount'

In [21]:
file=r'E:\lanchan VIP files\data scienece\python\Data\Existing Base.csv'

In [36]:
bd=pd.read_csv(file)

In [37]:
bd

REF_NO children age_band                status         occupation  \
0           1     Zero    51-55               Partner      Manual Worker   
1           2     Zero    55-60  Single/Never Married            Retired   
2           3     Zero    26-30  Single/Never Married       Professional   
3           5     Zero    18-21  Single/Never Married       Professional   
4           6     Zero    45-50               Partner   Business Manager   
5           7     Zero    55-60               Partner  Secretarial/Admin   
6           8     Zero    45-50               Partner       Professional   
7           9        1    36-40               Partner       Professional   
8          10     Zero    36-40  Single/Never Married  Secretarial/Admin   
9          11        2    36-40               Partner       Professional   
10         13     Zero    61-65               Partner            Retired   
11         14     Zero    45-50               Partner   Business Manager   
12         15     Zero    51-55               Widowed       Professional   
13         16     Zero    31-35  Single/Never Married      Manual Worker   
14         17        1    31-35               Partner  Secretarial/Admin   
15         18     Zero    26-30               Partner            Unknown   
16         19     Zero    41-45               Partner  Secretarial/Admin   
17         20     Zero    41-45    Divorced/Separated       Professional   
18         21        1    41-45               Partner  Secretarial/Admin   
19         23     Zero    41-45    Divorced/Separated  Secretarial/Admin   
20         26     Zero    26-30               Partner       Professional   
21         27        2    31-35               Partner   Business Manager   
22         28     Zero      71+               Partner            Retired   
23         29        3    36-40               Partner   Business Manager   
24         30        1    26-30               Partner  Secretarial/Admin   
25         31        1    22-25               Partner  Secretarial/Admin   
26         33        1    45-50               Partner      Manual Worker   
27         34     Zero    22-25               Partner       Professional   
28         35     Zero    65-70               Widowed            Retired   
29         36        2    36-40               Partner  Secretarial/Admin   
...       ...      ...      ...                   ...                ...   
10125   11484     Zero    51-55               Partner       Professional   
10126   11485        2    31-35               Partner       Professional   
10127   11486     Zero    51-55               Partner  Secretarial/Admin   
10128   11487     Zero    45-50               Partner              Other   
10129   11488     Zero    22-25  Single/Never Married       Professional   
10130   11489     Zero    51-55               Partner  Secretarial/Admin   
10131   11491     Zero      71+               Partner            Retired   
10132   11492     Zero    41-45               Partner  Secretarial/Admin   
10133   11493        2    22-25               Partner       Professional   
10134   11494        1    65-70               Partner  Secretarial/Admin   
10135   11495     Zero    45-50               Partner  Secretarial/Admin   
10136   11496        2    41-45               Partner       Professional   
10137   11497     Zero    26-30               Partner   Business Manager   
10138   11498        2    36-40    Divorced/Separated       Professional   
10139   11499     Zero    55-60               Widowed            Retired   
10140   11500     Zero    51-55               Partner            Retired   
10141   11501        1    18-21  Single/Never Married  Secretarial/Admin   
10142   11502        2    26-30               Partner            Unknown   
10143   11503        1    45-50               Partner   Business Manager   
10144   11504        1    51-55               Partner   Business Manager   
10145   11505     Zero    51-55               Partner  

In [24]:
bd['Revenue Grid'].value_counts()

2    9069
1    1086
Name: Revenue Grid, dtype: int64

In [25]:
bd.shape

(10155, 32)

In [26]:
bd['post_area'].value_counts()


PR5     35
PR4     33
TQ12    28
WA7     28
M12     26
WA4     26
BH23    25
LE7     25
M33     24
LE9     24
PR8     22
SK8     22
M14     21
HD7     21
M13     21
TS5     21
WA5     21
PR2     20
DY8     20
L12     20
NG9     20
PR6     20
L6      20
L13     20
WA3     20
PR7     20
CF62    20
L8      19
GL52    19
SL6     19
        ..
B48      1
LL48     1
B23      1
TW5      1
FK13     1
ST6      1
RH8      1
SW3      1
BT7      1
BD9      1
B49      1
FK15     1
DT10     1
DD4      1
PE15     1
WA40     1
TN17     1
KY14     1
KW9      1
NE48     1
KT11     1
NW10     1
IV6      1
NW8      1
AB34     1
EH44     1
HP8      1
WS2      1
NR27     1
CW4      1
Name: post_area, Length: 2039, dtype: int64

In [27]:
bd.dtypes

REF_NO                               int64
children                            object
age_band                            object
status                              object
occupation                          object
occupation_partner                  object
home_status                         object
family_income                       object
self_employed                       object
self_employed_partner               object
year_last_moved                      int64
TVarea                              object
post_code                           object
post_area                           object
Average Credit Card Transaction    float64
Balance Transfer                   float64
Term Deposit                       float64
Life Insurance                     float64
Medical Insurance                  float64
Average A/C Balance                float64
Personal Loan                      float64
Investment in Mutual Fund          float64
Investment Tax Saving Bond         float64
Home Loan  

In [28]:
list(zip(bd.columns,bd.dtypes,bd.nunique()))

[('REF_NO', dtype('int64'), 10155),
 ('children', dtype('O'), 5),
 ('age_band', dtype('O'), 13),
 ('status', dtype('O'), 5),
 ('occupation', dtype('O'), 9),
 ('occupation_partner', dtype('O'), 9),
 ('home_status', dtype('O'), 5),
 ('family_income', dtype('O'), 13),
 ('self_employed', dtype('O'), 2),
 ('self_employed_partner', dtype('O'), 2),
 ('year_last_moved', dtype('int64'), 95),
 ('TVarea', dtype('O'), 14),
 ('post_code', dtype('O'), 10040),
 ('post_area', dtype('O'), 2039),
 ('Average Credit Card Transaction', dtype('float64'), 1411),
 ('Balance Transfer', dtype('float64'), 2183),
 ('Term Deposit', dtype('float64'), 1419),
 ('Life Insurance', dtype('float64'), 3111),
 ('Medical Insurance', dtype('float64'), 1589),
 ('Average A/C Balance', dtype('float64'), 2223),
 ('Personal Loan', dtype('float64'), 1760),
 ('Investment in Mutual Fund', dtype('float64'), 2470),
 ('Investment Tax Saving Bond', dtype('float64'), 832),
 ('Home Loan', dtype('float64'), 884),
 ('Online Purchase Amount'

In [29]:
# REF_NO,post_code , post_area  : drop 
# children : Zero : 0 , 4+ : 4 and then convert to numeric
# age_band : dummies 
# status , occupation , occupation_partner , home_status,family_income : dummies
# self_employed, ` : dummies
# TVArea , Region , gender : dummies
# Revenue Grid : 1,2 : 1,0


In [38]:
bd.drop(['REF_NO','post_code','post_area'],axis=1,inplace=True)

In [39]:
#bd.loc[bd["children"]=="Zero","children"]="0"
#bd.loc[bd["children"]=="4+","children"]="4"
#bd["children"]=pd.to_numeric(bd["children"],errors="coerce")
bd['children'].value_counts()

Zero    6208
1       1848
2       1607
3        473
4+        19
Name: children, dtype: int64

In [40]:
bd['children']=np.where(bd['children']=='Zero','0',bd['children'])
bd['children']=np.where(bd['children']=='4+',4,bd['children'])
bd['children']=pd.to_numeric(bd['children'],errors='coerce')

In [41]:
bd['family_income'].value_counts()

>=35,000             2517
<27,500, >=25,000    1227
<30,000, >=27,500     994
<25,000, >=22,500     833
<20,000, >=17,500     683
<12,500, >=10,000     677
<17,500, >=15,000     634
<15,000, >=12,500     629
<22,500, >=20,000     590
<10,000, >= 8,000     563
< 8,000, >= 4,000     402
< 4,000               278
Unknown               128
Name: family_income, dtype: int64

In [42]:
k=bd['family_income'].str.split('>=',expand=True)

In [43]:
k

0       1
0      <17,500,   15,000
1      <27,500,   25,000
2      <30,000,   27,500
3      <15,000,   12,500
4      <30,000,   27,500
5      <17,500,   15,000
6                 35,000
7                 35,000
8      <17,500,   15,000
9                 35,000
10     <12,500,   10,000
11                35,000
12                35,000
13     <25,000,   22,500
14     <30,000,   27,500
15                35,000
16                35,000
17     <25,000,   22,500
18     <12,500,   10,000
19     <10,000,    8,000
20                35,000
21                35,000
22     <22,500,   20,000
23     <27,500,   25,000
24                35,000
25     <22,500,   20,000
26     <17,500,   15,000
27                35,000
28     <15,000,   12,500
29                35,000
...          ...     ...
10125  <25,000,   22,500
10126             35,000
10127  <30,000,   27,500
10128             35,000
10129             35,000
10130  <20,000,   17,500
10131  <12,500,   10,000
10132  <12,500,   10,000
10133  <30,000,   27,500
10134  <20,000,   17,500
10135  <17,500,   15,000
10136  <30,000,   27,500
10137  <30,000,   27,500
10138  <25,000,   22,500
10139  <22,500,   20,000
10140  <20,000,   17,500
10141    < 4,000    None
10142  <22,500,   20,000
10143  <30,000,   27,500
10144             35,000
10145  <30,000,   27,500
10146  <27,500,   25,000
10147  <27,500,   25,000
10148  < 8,000,    4,000
10149  <27,500,   25,000
10150  <30,000,   27,500
10151  <25,000,   22,500
10152             35,000
10153  <10,000,    8,000
10154  <27,500,   25,000

[10155 rows x 2 columns]

In [46]:
k[0]=k[0].str.replace('<','')
k[1]=k[1].str.replace('<','')
k[0]=k[0].str.replace(',','')
k[1]=k[1].str.replace(',','')

In [47]:
k

0      1
0      17500   15000
1      27500   25000
2      30000   27500
3      15000   12500
4      30000   27500
5      17500   15000
6              35000
7              35000
8      17500   15000
9              35000
10     12500   10000
11             35000
12             35000
13     25000   22500
14     30000   27500
15             35000
16             35000
17     25000   22500
18     12500   10000
19     10000    8000
20             35000
21             35000
22     22500   20000
23     27500   25000
24             35000
25     22500   20000
26     17500   15000
27             35000
28     15000   12500
29             35000
...       ...    ...
10125  25000   22500
10126          35000
10127  30000   27500
10128          35000
10129          35000
10130  20000   17500
10131  12500   10000
10132  12500   10000
10133  30000   27500
10134  20000   17500
10135  17500   15000
10136  30000   27500
10137  30000   27500
10138  25000   22500
10139  22500   20000
10140  20000   17500
10141    4000   None
10142  22500   20000
10143  30000   27500
10144          35000
10145  30000   27500
10146  27500   25000
10147  27500   25000
10148   8000    4000
10149  27500   25000
10150  30000   27500
10151  25000   22500
10152          35000
10153  10000    8000
10154  27500   25000

[10155 rows x 2 columns]

In [48]:
#where 1st column empty take from 2nd
#where ever its none also

k.loc[k[0]=='',0]=k[1]
k.loc[k[1].isnull(),1]=k[0]

In [49]:
k

0      1
0      17500   15000
1      27500   25000
2      30000   27500
3      15000   12500
4      30000   27500
5      17500   15000
6       35000  35000
7       35000  35000
8      17500   15000
9       35000  35000
10     12500   10000
11      35000  35000
12      35000  35000
13     25000   22500
14     30000   27500
15      35000  35000
16      35000  35000
17     25000   22500
18     12500   10000
19     10000    8000
20      35000  35000
21      35000  35000
22     22500   20000
23     27500   25000
24      35000  35000
25     22500   20000
26     17500   15000
27      35000  35000
28     15000   12500
29      35000  35000
...       ...    ...
10125  25000   22500
10126   35000  35000
10127  30000   27500
10128   35000  35000
10129   35000  35000
10130  20000   17500
10131  12500   10000
10132  12500   10000
10133  30000   27500
10134  20000   17500
10135  17500   15000
10136  30000   27500
10137  30000   27500
10138  25000   22500
10139  22500   20000
10140  20000   17500
10141    4000   4000
10142  22500   20000
10143  30000   27500
10144   35000  35000
10145  30000   27500
10146  27500   25000
10147  27500   25000
10148   8000    4000
10149  27500   25000
10150  30000   27500
10151  25000   22500
10152   35000  35000
10153  10000    8000
10154  27500   25000

[10155 rows x 2 columns]

In [50]:
k[0]=pd.to_numeric(k[0],errors='coerce')
k[1]=pd.to_numeric(k[1],errors='coerce')

bd['fi']=0.5*(k[0]+k[1])
del bd['family_income']

In [53]:
bd['Revenue Grid'].value_counts()

0    9069
1    1086
Name: Revenue Grid, dtype: int64

In [52]:
bd['Revenue Grid']=(bd['Revenue Grid']==1).astype(int)

In [54]:
cat_var=bd.select_dtypes(['object']).columns

In [55]:
cat_var

Index(['age_band', 'status', 'occupation', 'occupation_partner', 'home_status',
       'self_employed', 'self_employed_partner', 'TVarea', 'gender', 'region'],
      dtype='object')

In [56]:
for col in cat_var:
    dummy=pd.get_dummies(bd[col],drop_first=True,prefix=col)
    bd=pd.concat([bd,dummy],axis=1)
    del bd[col]
del dummy

In [57]:
bd.shape

(10155, 84)

In [58]:
from sklearn.model_selection import train_test_split

In [60]:
bd_train,bd_test=train_test_split(bd,test_size=0.2,random_state=2)
bd_train.isnull().sum()

children                             0
year_last_moved                      0
Average Credit Card Transaction      0
Balance Transfer                     0
Term Deposit                         0
Life Insurance                       0
Medical Insurance                    0
Average A/C Balance                  0
Personal Loan                        0
Investment in Mutual Fund            0
Investment Tax Saving Bond           0
Home Loan                            0
Online Purchase Amount               0
Revenue Grid                         0
Investment in Commudity              0
Investment in Equity                 0
Investment in Derivative             0
Portfolio Balance                    0
fi                                 107
age_band_22-25                       0
age_band_26-30                       0
age_band_31-35                       0
age_band_36-40                       0
age_band_41-45                       0
age_band_45-50                       0
age_band_51-55           

In [61]:
bd_test.isnull().sum()

children                            0
year_last_moved                     0
Average Credit Card Transaction     0
Balance Transfer                    0
Term Deposit                        0
Life Insurance                      0
Medical Insurance                   0
Average A/C Balance                 0
Personal Loan                       0
Investment in Mutual Fund           0
Investment Tax Saving Bond          0
Home Loan                           0
Online Purchase Amount              0
Revenue Grid                        0
Investment in Commudity             0
Investment in Equity                0
Investment in Derivative            0
Portfolio Balance                   0
fi                                 21
age_band_22-25                      0
age_band_26-30                      0
age_band_31-35                      0
age_band_36-40                      0
age_band_41-45                      0
age_band_45-50                      0
age_band_51-55                      0
age_band_55-

In [63]:
for col in ['children','fi']:
    bd_train.loc[bd_train[col].isnull(),col]=bd_train[col].mean()
    bd_test.loc[bd_test[col].isnull(),col]=bd_train[col].mean()

C:\Users\sujith\Anaconda3\lib\site-packages\pandas\core\indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [65]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

In [66]:
logr=LogisticRegression(class_weight='balanced')

In [68]:
x_train=bd_train.drop('Revenue Grid',axis=1)
y_train=bd_train['Revenue Grid']
x_test=bd_test.drop('Revenue Grid',axis=1)
y_test=bd_test['Revenue Grid']

In [70]:
logr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [71]:
logr.predict(x_test)

array([0, 0, 0, ..., 1, 1, 0])

In [78]:
logr.predict_proba(x_test)

array([[0.98420377, 0.01579623],
       [0.92370687, 0.07629313],
       [0.9244626 , 0.0755374 ],
       ...,
       [0.12980274, 0.87019726],
       [0.25209663, 0.74790337],
       [0.93463717, 0.06536283]])

In [79]:
logr.classes_

array([0, 1])

In [80]:
predicted_probs=logr.predict_proba(x_test)[:,1]

In [81]:
predicted_probs

array([0.01579623, 0.07629313, 0.0755374 , ..., 0.87019726, 0.74790337,
       0.06536283])

In [82]:
roc_auc_score(y_test,predicted_probs)

0.9462235156929402

In [83]:
cutoffs=np.linspace(0.001,0.99,99)
cutoffs

array([0.001     , 0.01109184, 0.02118367, 0.03127551, 0.04136735,
       0.05145918, 0.06155102, 0.07164286, 0.08173469, 0.09182653,
       0.10191837, 0.1120102 , 0.12210204, 0.13219388, 0.14228571,
       0.15237755, 0.16246939, 0.17256122, 0.18265306, 0.1927449 ,
       0.20283673, 0.21292857, 0.22302041, 0.23311224, 0.24320408,
       0.25329592, 0.26338776, 0.27347959, 0.28357143, 0.29366327,
       0.3037551 , 0.31384694, 0.32393878, 0.33403061, 0.34412245,
       0.35421429, 0.36430612, 0.37439796, 0.3844898 , 0.39458163,
       0.40467347, 0.41476531, 0.42485714, 0.43494898, 0.44504082,
       0.45513265, 0.46522449, 0.47531633, 0.48540816, 0.4955    ,
       0.50559184, 0.51568367, 0.52577551, 0.53586735, 0.54595918,
       0.55605102, 0.56614286, 0.57623469, 0.58632653, 0.59641837,
       0.6065102 , 0.61660204, 0.62669388, 0.63678571, 0.64687755,
       0.65696939, 0.66706122, 0.67715306, 0.6872449 , 0.69733673,
       0.70742857, 0.71752041, 0.72761224, 0.73770408, 0.74779

In [85]:
train_score=logr.predict_proba(x_train)[:,1]
real=y_train

In [94]:
KS_all=[]
for cutoff in cutoffs:
    predicted=(train_score>cutoff).astype(int)
    
    TP=((predicted==1) & (real==1)).sum()
    TN=((predicted==0) & (real==0)).sum()
    FP=((predicted==1) & (real==0)).sum()
    FN=((predicted==0) & (real==1)).sum()
    
    P=TP+FN
    N=TN+FP
    
    KS=(TP/P)-(FP/N)
    
    KS_all.append(KS)
    
# do this for fb
    

In [107]:
mycutoff=cutoffs[KS_all==max(KS_all)]
mycutoff

array([0.44504082])

In [96]:
logr.intercept_

array([-2.56703561])

In [97]:
list(zip(x_train.columns,logr.coef_[0]))

[('children', 0.060306256781727845),
 ('year_last_moved', -6.256108268815802e-05),
 ('Average Credit Card Transaction', 0.022248828726055096),
 ('Balance Transfer', -0.006501712756629205),
 ('Term Deposit', -0.02000572298713658),
 ('Life Insurance', 0.0017258751436014898),
 ('Medical Insurance', -0.024626997149354377),
 ('Average A/C Balance', -0.014500393726365185),
 ('Personal Loan', -0.04473060921991578),
 ('Investment in Mutual Fund', -0.012710647145894788),
 ('Investment Tax Saving Bond', 0.0798395059164786),
 ('Home Loan', -0.08181143958948377),
 ('Online Purchase Amount', 0.05726882535727951),
 ('Investment in Commudity', 0.006396723422552624),
 ('Investment in Equity', 0.002347904326007628),
 ('Investment in Derivative', 0.073115508236388),
 ('Portfolio Balance', -0.0002720663524674196),
 ('fi', 4.205460515724539e-06),
 ('age_band_22-25', -0.4274708327825343),
 ('age_band_26-30', -0.20467330212585733),
 ('age_band_31-35', -0.4908244479981635),
 ('age_band_36-40', -0.42370105558

In [101]:
test_score=logr.predict_proba(x_test)[:,1]

In [102]:
pd.DataFrame(test_score).to_csv("E:\lanchan VIP files\data scienece\python\Data\mysub\mylogisticsubmission.csv",index=False)

if you had to submit hardclasses , you can apply the cutoff obtained above and then submit

In [108]:
test_classes=(test_score>mycutoff).astype(int)

In [110]:
pd.DataFrame(test_classes).to_csv("E:\lanchan VIP files\data scienece\python\Data\mysub\mylogisticsubmission1.csv",index=False)